In [1]:
import pandas as pd

In [9]:
data = pd.read_csv('.\981019.csv')
data.describe()

,match_id,season,innings,ball,runs_off_bat,extras,wides,noballs,byes,legbyes,penalty,other_wicket_type,other_player_dismissed
count,250.0,250.0,250.000000,250.000000,250.000000,250.000,10.000000,0.0,1.0,7.0,0.0,0.0,0.0
mean,981019.0,2016.0,1.496000,9.824800,1.540000,0.092,1.500000,NaN,1.0,1.0,NaN,NaN,NaN
std,0.0,0.0,0.500987,5.845235,1.894931,0.415,1.269296,NaN,NaN,0.0,NaN,NaN,NaN
min,981019.0,2016.0,1.000000,0.100000,0.000000,0.000,1.000000,NaN,1.0,1.0,NaN,NaN,NaN
25%,981019.0,2016.0,1.000000,4.600000,0.000000,0.000,1.000000,NaN,1.0,1.0,NaN,NaN,NaN
50%,981019.0,2016.0,1.000000,9.600000,1.000000,0.000,1.000000,NaN,1.0,1.0,NaN,NaN,NaN
75%,981019.0,2016.0,2.000000,15.100000,2.000000,0.000,1.000000,NaN,1.0,1.0,NaN,NaN,NaN
max,981019.0,2016.0,2.000000,19.600000,6.000000,5.000,5.000000,NaN,1.0,1.0,NaN,NaN,NaN

In [7]:
print(data['season', 'run'])

KeyError: ('season', 'run')